steps:
  # Npm install
  - name: "gcr.io/cloud-builders/npm"
    args: ["install", "--production"]

  # Build production optimized site
  - name: "gcr.io/cloud-builders/npm"
    args: ["run", "build"]
    env:
      - "REACT_APP_VERSION=$TAG_NAME"

  # Package Docker image
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "$_REGION/$PROJECT_ID/$_IMAGE_NAME:$TAG_NAME", "."]

  # Push the docker image to the registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "$_REGION/$PROJECT_ID/$_IMAGE_NAME:$TAG_NAME"]

  # DEPLOY to Server
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "beta",
        "compute",
        "instances",
        "update-container",
        "$_SERVER_INSTANCE_NAME",
        "--zone",
        "$_ZONE",
        "--container-image=$_REGION/$PROJECT_ID/$_IMAGE_NAME:$TAG_NAME",
      ]
    env:
      - "PORT=$_PORT"
