steps:
  # Npm install
  - name: "gcr.io/cloud-builders/npm"
    args: ["install", "--production"]

  # Build production optimized site
  - name: "gcr.io/cloud-builders/npm"
    args: ["run", "build"]

  # Package Docker image
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "$_ZONE/$PROJECT_ID/$_IMAGE_NAME:$TAG_NAME", "."]
    env:
      - "PORT=$_PORT"

  # Push the docker image to the registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "$_ZONE/$PROJECT_ID/$_IMAGE_NAME:$TAG_NAME"]
