steps:
  # Build the docker image
  - name: "$_ZONE/cloud-builders/docker"
    args: ["build", "-t", "$_ZONE/$PROJECT_ID/$_IMAGE_NAME:$TAG_NAME", "."]
    images:
      - "$_ZONE/$PROJECT_ID/$_IMAGE_NAME:$TAG_NAME"
    env:
      - "PORT=$_PORT"

  # Push the docker image to the registry
  - name: "$_ZONE/cloud-builders/docker"
    args: ["push", "$_ZONE/$PROJECT_ID/$_IMAGE_NAME:$TAG_NAME"]
