# Build process for deploying to GKE

steps:
  # Npm install
  - name: "gcr.io/cloud-builders/npm"
    args: ["install", "--production"]

  # Build production optimized site
  - name: "gcr.io/cloud-builders/npm"
    args: ["run", "build"]
    env:
      - "REACT_APP_VERSION=$TAG_NAME"

  # Package Docker image
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "$_REGION/$PROJECT_ID/$_IMAGE_NAME:$TAG_NAME", "."]

  # Push the docker image to the registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "$_REGION/$PROJECT_ID/$_IMAGE_NAME:$TAG_NAME"]

  # Perform rolling update to Kubernetes
  - name: "gcr.io/cloud-builders/kubectl"
    args: ["set", 
    "image",
    "deployment",
    "$_IMAGE_NAME=$_REGION/$PROJECT_ID/$_IMAGE_NAME:$TAG_NAME"]
    env:
      - "CLOUDSDK_CONTAINER_CLUSTER=$_CLOUDSDK_CONTAINER_CLUSTER"
      - "CLOUDSDK_COMPUTE_ZONE=$_ZONE"