const INIT_BOARD = "INIT_BOARD",
  MOVE = "MOVE",
  REPLAY = "REPLAY",
  ANIMATEMOVE = "ANIMATEMOVE",
  DRAGSTART = "DRAGSTART",
  CLEARHIGHLIGHT = "CLEARHIGHLIGHT";

module.exports = {
  ANIMATEMOVE,
  CLEARHIGHLIGHT,
  DRAGSTART,
  INIT_BOARD,
  MOVE,
  REPLAY
};
